### Create ticket
POST http://localhost:3002/api/tickets/create
Content-Type: application/json

{
  "topic": "12312313",
  "message": "asdasdasdasdasdasdads"
}

### In progress ticket
PUT http://localhost:3002/api/tickets/progress
Content-Type: application/json

{
  "id": 1
}

### Complete ticket
PUT http://localhost:3002/api/tickets/complete
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

### Cancel ticket
PUT http://localhost:3002/api/tickets/cancel
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

### Cancel all tickets
PUT http://localhost:3002/api/tickets/cancel-all
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

### Get all tickets
GET http://localhost:3002/api/tickets/
Content-Type: application/json