### Create ticket
POST http://localhost:3002/api/tickets/create
Content-Type: application/json

{
  "topic": "12312313",
  "message": "asdasdasdasdasdasdads"
}

### In progress ticket
PUT http://localhost:3002/api/tickets/progress
Content-Type: application/json

{
  "id": 5
}

### Complete ticket
PUT http://localhost:3002/api/tickets/complete
Content-Type: application/json

{
  "id": 3,
  "resolution": "this is genius resolution"
}

### Cancel ticket
PUT http://localhost:3002/api/tickets/cancel
Content-Type: application/json

{
  "id": 1,
  "cancelledReason": "cancelled because i feel bored"
}

### Cancel all tickets
PUT http://localhost:3002/api/tickets/cancel-all
Content-Type: application/json

{
  "cancelledReason": "all cancel reason is this"
}

### Get all with filter by one day
GET http://localhost:3002/api/tickets/?fromDate=2025-05-21T00:00:00.000Z&toDate=2025-05-21T23:59:00.000Z
Accept: application/json

### Get all with filter by range of dates
GET http://localhost:3002/api/tickets/?fromDate=2025-05-10&toDate=2025-05-30
Accept: application/json